apiVersion: v2
name: msgboard
description: A Helm chart for Message Board Sample
type: application
version: 1.0.0
appVersion: 1.0.0

dependencies:
- name: ingress-nginx
  version: 2.11.1
  repository: https://kubernetes.github.io/ingress-nginx/
