apiVersion: apps/v1
kind: Deployment
{{- $fullName := include "msgboard.fullname" . }}
metadata:
  name: {{ $fullName }}-mssql
  labels:
    {{- include "msgboard.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "msgboard.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: database
  template:
    metadata:
      labels:
        {{- include "msgboard.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: database
    spec:
      serviceAccountName: {{ include "msgboard.serviceAccountName" . }}
      securityContext:
        fsGroup: 10001
      containers:
        - name: {{ .Chart.Name }}-mssql
          image: {{ .Values.mssql.image }}
          env:
            - name: ACCEPT_EULA
              value: {{ .Values.mssql.ACCEPT_EULA | quote }}
            {{- if .Values.mssql.MSSQL_PID }}
            - name: MSSQL_PID
              value: {{ .Values.mssql.MSSQL_PID | quote }}
            {{- end }}
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}-mssql-credential
                  key: password
          ports:
            - name: mssql
              containerPort: 1433
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 1433
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: 1433
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.mssql.resources | nindent 12 }}
          volumeMounts:
            - mountPath: "/var/opt/mssql"
              name: mssqldb
      volumes:
        - name: mssqldb
          persistentVolumeClaim:
            claimName: {{ $fullName }}-mssql-claim
      nodeSelector:
        kubernetes.io/os: linux
      {{- with .Values.mssql.nodeSelector }}
        {{- toYaml . | nindent 8 }}
      {{- end -}}
