apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "msgboard.fullname" . }}-mssql-claim
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.mssql.storage.className }}
  resources:
    requests:
      storage: {{ .Values.mssql.storage.size }}
