apiVersion: v1
kind: Secret
metadata:
  name: {{ include "msgboard.fullname" . }}-mssql-credential
type: Opaque
data:
{{- with .Values.mssql.credential }}
  username: {{ .username | b64enc }}
  password: {{ .password | b64enc }}
{{- end }}
