{{- if .Values.ingress.enabled -}}
{{- if .Values.ingress.tls.key -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "msgboard.fullname" . }}-tls
type: kubernetes.io/tls
data:
{{- with .Values.ingress.tls }}
  tls.crt: {{ .certificate | b64enc }}
  tls.key: {{ .key | b64enc }}
{{- end }}
{{- end }}
{{- end }}
