apiVersion: v1
kind: Secret
{{- $fullName := include "msgboard.fullname" . }}
metadata:
  name: {{ $fullName }}-mssql-connection-string
type: Opaque
data:
  {{- $template := "Data Source=%s-mssql;Initial Catalog=msgs;User ID=%s;Password=%s;MultipleActiveResultSets=True;App=EntityFramework" -}}
  {{- with .Values.mssql.credential }}
  connection-string: {{ printf $template $fullName .username .password | b64enc }}
  {{- end -}}
