apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "msgboard.labels" . | nindent 4 }}
spec:
  {{- if or .Values.nginx.create .Values.ingress.enabled }}
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  {{- else }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  {{- end }}
  selector:
    {{- include "msgboard.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: controller
