{{- if .Values.nginx.create -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "msgboard.fullname" . }}-nginx
  labels:
    {{- include "msgboard.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "msgboard.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: reverse-proxy
{{- end -}}
