apiVersion: v1
kind: Service
metadata:
  name: {{ include "msgboard.fullname" . }}-mssql
  labels:
    {{- include "msgboard.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 1433
      targetPort: 1433
      protocol: TCP
      name: mssql
  selector:
    {{- include "msgboard.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
